site_name: NCR Digital Ordering
site_url: https://www.ncr.com
site_description: Technical Documentation and Release Notes for NCR Digital Ordering
site_author: NCR

theme: gitbook

copyright: Copyright &copy; 2020 NCR Corporation. All rights reserved.
